### ISSUE TITLE
NoClassDefFoundError for Intellij$IEq_IElementType

### ISSUE THREAD

**Issue by carymrobbins** [carymrobbins/intellij-frege#4]
For reference, here's the [instance Eq IElementType](https://github.com/carymrobbins/intellij-frege/blob/5306a7031d43d32278dc35ddef601eafdffb59d1/frege-bindings/src/com/haskforce/frege/bindings/Intellij.fr#L29-L30).

```
com/haskforce/frege/bindings/Intellij$IEq_IElementType
java.lang.NoClassDefFoundError: com/haskforce/frege/bindings/Intellij$IEq_IElementType
    at com.haskforce.frege.lang.parser.FregeParser.lambda$null$0(FregeParser.java:130)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.Builder.lambda$null$18(Builder.java:854)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.Builder.lambda$null$19(Builder.java:861)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.Builder$IMonad_Builder.lambda$null$26(Builder.java:551)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10263)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$null$2(PreludeBase.java:10264)
    at frege.run8.Thunk.call(Thunk.java:231)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$performUnsafe$4(PreludeBase.java:10268)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.FregePsiParser.parse(FregePsiParser.java:16)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.a(LazyParseableElement.java:172)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
    at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
    at idea.plugin.psiviewer.view.PsiViewerPanel.selectElementAtCaret(PsiViewerPanel.java:326)
    at idea.plugin.psiviewer.view.PsiViewerPanel.selectElementAtCaret(PsiViewerPanel.java:312)
    at idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent.handleCurrentState(PsiViewerProjectComponent.java:153)
    at idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent.access$000(PsiViewerProjectComponent.java:50)
    at idea.plugin.psiviewer.controller.project.PsiViewerProjectComponent$1.propertyChange(PsiViewerProjectComponent.java:103)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8430)
    at javax.swing.JComponent.addNotify(JComponent.java:4741)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addImpl(Container.java:1121)
    at java.awt.Container.add(Container.java:417)
    at com.intellij.openapi.ui.ThreeComponentsSplitter.setLastComponent(ThreeComponentsSplitter.java:432)
    at com.intellij.openapi.wm.impl.ToolWindowsPane.a(ToolWindowsPane.java:378)
    at com.intellij.openapi.wm.impl.ToolWindowsPane.access$500(ToolWindowsPane.java:57)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddDockedComponentCmd.run(ToolWindowsPane.java:752)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.haskforce.frege.bindings.Intellij$IEq_IElementType PluginClassLoader[com.haskforce.frege, 0.0-SNAPSHOT]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 76 more



java.lang.NoClassDefFoundError: com/haskforce/frege/bindings/Intellij$IEq_IElementType
    at com.haskforce.frege.lang.parser.FregeParser.lambda$null$0(FregeParser.java:130)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.Builder.lambda$null$18(Builder.java:854)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.Builder.lambda$null$19(Builder.java:861)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.Builder$IMonad_Builder.lambda$null$26(Builder.java:551)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10263)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$null$2(PreludeBase.java:10264)
    at frege.run8.Thunk.call(Thunk.java:231)
    at frege.prelude.PreludeBase$TST.lambda$$gt$gt$eq$3(PreludeBase.java:10262)
    at frege.prelude.PreludeBase$TST.lambda$performUnsafe$4(PreludeBase.java:10268)
    at frege.run8.Thunk.call(Thunk.java:231)
    at com.haskforce.frege.lang.parser.FregePsiParser.parse(FregePsiParser.java:16)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.a(LazyParseableElement.java:172)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:468)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.a(CollectHighlightsUtil.java:160)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.findCommonParent(CollectHighlightsUtil.java:139)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.getElementsInRange(CollectHighlightsUtil.java:53)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.getElementsInRange(CollectHighlightsUtil.java:45)
    at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by carymrobbins** [comment]
Mysteriously, after some rebuilds it seems to be working now.
